name: Context

on:
 workflow_dispatch
env:
 MY_VAR: 'workflow'
jobs:
 print:
  strategy:
   matrix:
    os:
    - ubuntu-latest
    - windows-latest

  runs-on: ${{matrix.os}}
  steps:
    
   - name: Print Info
     env:
      MY_VAR: 'steps'
     run: |
      echo 'event that triggered this workflow ${{github.event_name}}'
      echo 'Actor - user who has triggered ${{github.actor}}'
      echo 'SHA value ${{github.sha}}'
      echo 'header details ${{github.ref}}'
      echo 'Runner id ${{github.run_id}}'
      echo 'runner number is ${{github.run_number}}'
      echo '${{github.triggering_actor}}'
      echo 'ENV var is ${{vars.MY_VAR}}'
      echo 'Secret is ${{secrets.PAT}}'
      echo 'Matrix value ${{matrix.os}}'
