name: Env

run-name: DEBUG | ${{inputs.debug}}
on:
 workflow_dispatch:
  inputs:
   TAR_ENV:
    type: environment
    default: staging
   debug:
    type: boolean
    default: false
jobs:
 env-info:
  runs-on: ubuntu-latest
  environment:  ${{inputs.TAR_ENV}}
  steps:
   - name: Print vars and secret for environment
     run:  |
      echo 'Var value is ${{vars.var}}'
   
