name: First Workflow

on: [pull_request, push,workflow_dispatch]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Step 1
     run: echo 'Step 1'
   - name: Step 2
     run: echo 'Step 2'
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
       java-version: 17
       distribution: microsoft
   - name: Java Version check
     run: echo java --version
     
 test:
  runs-on: windows-latest
  steps:
   - name: Step 1
     run: echo 'Step 1'
   - name: Step 2
     run: echo 'Step 2'
  
