name: First Workflow

on:
 push:
  branches:
   - master

jobs:
 build:
  strategy:
   fail-fast: false
   matrix:
     java-version: [17,21,26]
  runs-on: ubuntu-latest
  steps:
   - name: Step 1
     run: echo 'Step 1'
   - name: Step 2
     run: echo 'Step 2'
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
       java-version: ${{matrix.java-version}}
       distribution: microsoft
   - name: Java Version check
     run: echo java --version
     
 test:
  needs: build
  runs-on: windows-latest
  steps:
   - name: Step 1
     run: echo 'Step 1'
   - name: Step 2
     run: echo 'Step 2'
  
